apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: iterate-sample
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=iterate-sample"
spec:
  type: service
  lifecycle: experimental
  owner: default-team
